defmodule EveDmv.Repo.Migrations.AddShipFittingsTable do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:ship_fittings, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:name, :text, null: false)
      add(:ship_type_id, :bigint, null: false)
      add(:character_id, :bigint)
      add(:source, :text, default: "manual")
      add(:raw_fitting, :text, null: false)
      add(:parsed_fitting, :map, default: %{})
      add(:calculated_stats, :map, default: %{})
      add(:last_calculated, :utc_datetime_usec)
      add(:tags, {:array, :text}, default: [])
      add(:is_public, :boolean, default: false)
      add(:usage_count, :bigint, default: 0)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end
  end

  def down do
    drop(table(:ship_fittings))
  end
end
