defmodule EveDmv.Repo.Migrations.AddWormholeEffectType do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:eve_solar_systems) do
      add(:wormhole_effect_type, :text)
    end
  end

  def down do
    alter table(:eve_solar_systems) do
      remove(:wormhole_effect_type)
    end
  end
end
