defmodule EveDmv.Repo.Migrations.AddWormholeClassId do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:eve_solar_systems) do
      add(:wormhole_class_id, :bigint)
    end
  end

  def down do
    alter table(:eve_solar_systems) do
      remove(:wormhole_class_id)
    end
  end
end
