# Dialyzer ignore file
# Generated from `mix dialyzer --format ignore_file`
#
# These warnings are suppressed because they are either:
# 1. False positives from MapSet opaque type handling
# 2. Cascading type analysis issues from with chains
# 3. Intentional contract supertypes for flexibility
# 4. Pattern match coverage on multi-clause functions that work at runtime

[
  # MapSet opaque type false positives
  {"lib/eve_dmv/contexts.ex", :call_without_opaque},
  {"lib/eve_dmv/contexts/battle_analysis/domain/multi_system_battle_correlator.ex",
   :call_without_opaque},
  {"lib/eve_dmv/contexts/battle_analysis/domain/multi_system_battle_correlator.ex",
   :call_with_opaque},
  {"lib/eve_dmv/contexts/battle_analysis/domain/strategic/correlation_engine.ex",
   :call_without_opaque},
  {"lib/eve_dmv/contexts/character_intelligence/domain/analyzers/cross_character_analyzer.ex",
   :call_without_opaque},
  {"lib/eve_dmv/contexts/combat_intelligence/domain/ewar_analyzer.ex", :call_without_opaque},
  {"lib/eve_dmv/contexts/intelligence_infrastructure/domain/cross_system/cross_system_coordinator.ex",
   :call_without_opaque},

  # Pattern match issues - cascading from with chains
  {"lib/eve_dmv/application.ex", :pattern_match},
  {"lib/eve_dmv/contexts/battle_analysis.ex", :pattern_match},
  {"lib/eve_dmv/contexts/battle_analysis.ex", :pattern_match_cov},
  {"lib/eve_dmv/contexts/battle_analysis/domain/battle_metrics_calculator.ex", :pattern_match},
  {"lib/eve_dmv/contexts/battle_sharing/domain/battle_curator.ex", :pattern_match},
  {"lib/eve_dmv/contexts/character_intelligence.ex", :pattern_match},
  {"lib/eve_dmv/contexts/character_intelligence.ex", :pattern_match_cov},
  {"lib/eve_dmv/contexts/character_intelligence/domain/engines/player_stats_engine.ex",
   :pattern_match},
  {"lib/eve_dmv/contexts/character_intelligence/domain/threat_scoring/shared_utilities.ex",
   :pattern_match},
  {"lib/eve_dmv/contexts/character_intelligence/resources/character_stats.ex", :pattern_match},
  {"lib/eve_dmv/contexts/character_intelligence/resources/character_stats.ex",
   :pattern_match_cov},
  {"lib/eve_dmv/contexts/combat/core/tactical_pattern_detector.ex", :pattern_match_cov},
  {"lib/eve_dmv/contexts/combat/services/doctrine_effectiveness_service.ex", :pattern_match},
  {"lib/eve_dmv/contexts/combat_intelligence/domain/extractors/killmail_extractor.ex",
   :pattern_match},
  {"lib/eve_dmv/contexts/corporation/core/threat_detector.ex", :pattern_match},
  {"lib/eve_dmv/contexts/corporation/services/analytics_service.ex", :pattern_match},
  {"lib/eve_dmv/contexts/corporation_intelligence.ex", :pattern_match},
  {"lib/eve_dmv/contexts/corporation_intelligence/domain/analyzers/corporation_analyzer.ex",
   :pattern_match},
  {"lib/eve_dmv/contexts/corporation_intelligence/domain/combat_doctrine/threat_assessor.ex",
   :pattern_match_cov},
  {"lib/eve_dmv/contexts/corporation_intelligence/domain/combat_doctrine_analyzer.ex",
   :pattern_match},
  {"lib/eve_dmv/contexts/corporation_intelligence/domain/combat_doctrine_analyzer.ex",
   :pattern_match_cov},
  {"lib/eve_dmv/contexts/intelligence_infrastructure/domain/analyzers/single_system_analyzer.ex",
   :pattern_match},
  {"lib/eve_dmv/contexts/killmail_processing/domain/killmail_orchestrator.ex",
   :pattern_match_cov},
  {"lib/eve_dmv/contexts/killmail_processing/domain/killmail_presenter.ex", :pattern_match},
  {"lib/eve_dmv/contexts/market_intelligence/domain/price_service.ex", :pattern_match},
  {"lib/eve_dmv/contexts/player_profile/domain/player_analyzer.ex", :pattern_match},
  {"lib/eve_dmv/contexts/surveillance/domain/alert_batcher.ex", :pattern_match},
  {"lib/eve_dmv/contexts/surveillance/domain/chain_intelligence.ex", :pattern_match},
  {"lib/eve_dmv/contexts/surveillance/infrastructure/notification_dispatcher.ex", :pattern_match},
  {"lib/eve_dmv/contexts/system_analysis/domain/regional_correlation_analyzer.ex",
   :pattern_match},
  {"lib/eve_dmv/contexts/threat_assessment/analyzers/threat_analyzer.ex", :pattern_match},
  {"lib/eve_dmv/contexts/threat_assessment/domain/threat_analyzer.ex", :pattern_match},
  {"lib/eve_dmv/contexts/threat_surveillance/domain/behavioral_pattern_analyzer.ex",
   :pattern_match},
  {"lib/eve_dmv/contexts/threat_surveillance/domain/surveillance_matching_engine.ex",
   :pattern_match_cov},
  {"lib/eve_dmv/core/domain/intelligence/core/correlation_engine.ex", :pattern_match},
  {"lib/eve_dmv/core/domain/intelligence/intelligence_scoring/intelligence_suitability.ex",
   :pattern_match_cov},
  {"lib/eve_dmv/core/refactoring/module_reorganizer.ex", :pattern_match},
  {"lib/eve_dmv/core/services/battle_service.ex", :pattern_match},
  {"lib/eve_dmv/core/utils/dns_resolver.ex", :pattern_match},
  {"lib/eve_dmv/external/eve/esi_market_client.ex", :pattern_match},
  {"lib/eve_dmv/external/eve/esi_request_client.ex", :pattern_match},
  {"lib/eve_dmv/external/eve/static_data_loader.ex", :pattern_match},
  {"lib/eve_dmv/external/eve/static_data_loader/ccp_sde_client.ex", :pattern_match},
  {"lib/eve_dmv/external/eve/static_data_loader/item_type_processor.ex", :pattern_match},
  {"lib/eve_dmv/external/eve/static_data_loader/jsonl_parser.ex", :pattern_match},
  {"lib/eve_dmv/external/eve/static_data_loader/sde_startup_service.ex", :pattern_match},
  {"lib/eve_dmv/external/eve/static_data_loader/sde_validator.ex", :pattern_match},
  {"lib/eve_dmv/external/eve/static_data_loader/sde_version_manager.ex", :pattern_match},
  {"lib/eve_dmv/external/eve/static_data_loader/solar_system_processor.ex", :pattern_match},
  {"lib/eve_dmv/external/market/strategies/esi_strategy.ex", :pattern_match},
  {"lib/eve_dmv/external/wanderer/wanderer_client.ex", :pattern_match},
  {"lib/eve_dmv/platform/auth/security/api_authentication.ex", :pattern_match},
  {"lib/eve_dmv/platform/auth/user.ex", :pattern_match_cov},
  {"lib/eve_dmv/platform/auth/user.ex", :pattern_match},
  {"lib/eve_dmv/platform/monitoring/error_recovery_worker.ex", :pattern_match_cov},
  {"lib/eve_dmv/platform/monitoring/performance_optimizer.ex", :pattern_match},
  {"lib/eve_dmv/platform/workers/background_task_supervisor.ex", :pattern_match_cov},
  {"lib/eve_dmv/platform/workers/ship_role_analysis_worker.ex", :pattern_match_cov},
  {"lib/eve_dmv/static_data/ship_attribute_importer.ex", :pattern_match},
  {"lib/eve_dmv/static_data/ship_attributes_service.ex", :pattern_match},

  # Contract supertype - intentional for API flexibility
  {"lib/eve_dmv/contexts/character_intelligence.ex", :contract_supertype},
  {"lib/eve_dmv/contexts/character_intelligence/domain/calculators/threat_score_calculator.ex",
   :contract_supertype},
  {"lib/eve_dmv/contexts/character_intelligence/threat_config.ex", :contract_supertype},
  {"lib/eve_dmv/contexts/combat_intelligence/api.ex", :contract_supertype},
  {"lib/eve_dmv/contexts/combat_intelligence/domain/external_group_analyzer.ex",
   :contract_supertype},
  {"lib/eve_dmv/contexts/combat_intelligence/domain/intelligence_transformer.ex",
   :contract_supertype},
  {"lib/eve_dmv/contexts/corporation_intelligence.ex", :contract_supertype},
  {"lib/eve_dmv/contexts/corporation_intelligence/api.ex", :contract_supertype},
  {"lib/eve_dmv/contexts/corporation_intelligence/domain/analyzers/corporation_analyzer.ex",
   :contract_supertype},
  {"lib/eve_dmv/contexts/fleet_operations/domain/analyzers/fleet_asset_manager/requirements_builder.ex",
   :contract_supertype},
  {"lib/eve_dmv/contexts/intelligence_infrastructure/domain/correlators/activity_correlator.ex",
   :contract_supertype},
  {"lib/eve_dmv/contexts/killmail_processing/domain/extended_historical_fetcher.ex",
   :contract_supertype},
  {"lib/eve_dmv/contexts/killmail_processing/domain/historical_fetch_worker.ex",
   :contract_supertype},
  {"lib/eve_dmv/contexts/market_intelligence/api.ex", :contract_supertype},
  {"lib/eve_dmv/contexts/player_profile/api.ex", :contract_supertype},
  {"lib/eve_dmv/contexts/system_analysis.ex", :contract_supertype},
  {"lib/eve_dmv/contexts/threat_surveillance/api.ex", :contract_supertype},
  {"lib/eve_dmv/core/analysis/data_requirements.ex", :contract_supertype},
  {"lib/eve_dmv/core/domain/analytics/pattern_analysis.ex", :contract_supertype},
  {"lib/eve_dmv/core/domain/intelligence/core/cache_helper.ex", :contract_supertype},
  {"lib/eve_dmv/core/domain/intelligence/core/config.ex", :contract_supertype},
  {"lib/eve_dmv/core/domain/intelligence/core/timeout_helper.ex", :contract_supertype},
  {"lib/eve_dmv/core/infrastructure/unified_cache.ex", :contract_supertype},
  {"lib/eve_dmv/core/infrastructure/unified_event_processor.ex", :contract_supertype},
  {"lib/eve_dmv/core/infrastructure/unified_repository.ex", :contract_supertype},
  {"lib/eve_dmv/core/shared_kernel/policies/security_classification.ex", :contract_supertype},
  {"lib/eve_dmv/core/shared_kernel/policies/threat_classification.ex", :contract_supertype},
  {"lib/eve_dmv/core/utils/naive_datetime_utils.ex", :contract_supertype},
  {"lib/eve_dmv/core/utils/number_formatter.ex", :contract_supertype},
  {"lib/eve_dmv/external/eve/name_resolver/cache_manager.ex", :contract_supertype},
  {"lib/eve_dmv/external/eve/static_data_loader/file_manager.ex", :contract_supertype},
  {"lib/eve_dmv/external/eve/static_data_loader/item_type_processor.ex", :contract_supertype},
  {"lib/eve_dmv/external/eve/static_data_loader/sde_validator.ex", :contract_supertype},
  {"lib/eve_dmv/external/killmails/pipeline_autoscaler_config.ex", :contract_supertype},
  {"lib/eve_dmv/platform/database/query_optimizer.ex", :contract_supertype},
  {"lib/eve_dmv/platform/database/query_plan_analyzer.ex", :contract_supertype},
  {"lib/eve_dmv/platform/monitoring/health_config.ex", :contract_supertype},
  {"lib/eve_dmv/result.ex", :contract_supertype},
  {"lib/eve_dmv/utilities/calculators/metrics_calculator.ex", :contract_supertype},

  # Extra range - intentional for polymorphic returns
  {"lib/eve_dmv/contexts/combat_intelligence/domain/character_analyzer.ex", :extra_range},
  {"lib/eve_dmv/contexts/surveillance/api.ex", :extra_range},
  {"lib/eve_dmv/core/shared_kernel/policies/security_classification.ex", :extra_range},
  {"lib/eve_dmv/external/eve/circuit_breaker.ex", :extra_range},
  {"lib/eve_dmv/external/eve/static_data_loader.ex", :extra_range},
  {"lib/eve_dmv/external/eve/static_data_loader/item_type_processor.ex", :extra_range},
  {"lib/eve_dmv/external/eve/static_data_loader/jsonl_parser.ex", :extra_range},
  {"lib/eve_dmv/external/eve/static_data_loader/sde_validator.ex", :extra_range},
  {"lib/eve_dmv/external/eve/static_data_loader/solar_system_processor.ex", :extra_range},
  {"lib/eve_dmv/platform/auth/account_manager.ex", :extra_range},

  # Invalid contract - functions work at runtime but dialyzer can't trace types
  {"lib/eve_dmv/contexts/corporation/api.ex", :invalid_contract},
  {"lib/eve_dmv/contexts/intelligence/api.ex", :invalid_contract},
  {"lib/eve_dmv/contexts/surveillance/api.ex", :invalid_contract},
  {"lib/eve_dmv/contexts/threat_surveillance/api.ex", :invalid_contract},

  # Guard fail - false positives in pattern matching with guards
  {"lib/eve_dmv/contexts/intelligence/services/insight_generator.ex", :guard_fail},
  {"lib/eve_dmv/core/refactoring/module_reorganizer.ex", :guard_fail},

  # Call issues - Ash framework internals
  {"lib/eve_dmv/external/eve/static_data_loader/jsonl_parser.ex", :call},
  {"lib/eve_dmv/platform/database/character_repository.ex", :call},
  {"lib/eve_dmv/platform/database/killmail_repository.ex", :call},

  # No return - functions that always raise or never return
  {"lib/eve_dmv/platform/database/character_repository.ex", :no_return},
  {"lib/eve_dmv/platform/database/killmail_repository.ex", :no_return},

  # Call to missing - optional dependencies
  {"lib/eve_dmv/external/killmails/participant.ex", :call_to_missing},

  # Web layer pattern matching
  {"lib/eve_dmv_web/components/battle_timeline_component.ex", :pattern_match_cov},
  {"lib/eve_dmv_web/controllers/api/battle_intelligence_controller.ex", :pattern_match_cov},
  {"lib/eve_dmv_web/controllers/api/battle_share_controller.ex", :pattern_match},
  {"lib/eve_dmv_web/controllers/api/character_behavior_controller.ex", :pattern_match_cov},
  {"lib/eve_dmv_web/controllers/api/character_threat_controller.ex", :pattern_match},
  {"lib/eve_dmv_web/controllers/api/character_threat_controller.ex", :pattern_match_cov},
  {"lib/eve_dmv_web/controllers/auth_controller.ex", :pattern_match},
  {"lib/eve_dmv_web/live/battle_analysis_live.ex", :pattern_match},
  {"lib/eve_dmv_web/live/battle_analysis_live.ex", :pattern_match_cov},
  {"lib/eve_dmv_web/live/character_comparison_live.ex", :pattern_match},
  {"lib/eve_dmv_web/live/character_intelligence_live.ex", :pattern_match},
  {"lib/eve_dmv_web/live/character_intelligence_live.ex", :contract_supertype},
  {"lib/eve_dmv_web/live/helpers/liveview_pattern_template.ex", :pattern_match},
  {"lib/eve_dmv_web/live/killmail_live.ex", :pattern_match_cov},
  {"lib/eve_dmv_web/live/profile_live.ex", :pattern_match_cov},
  {"lib/eve_dmv_web/live/unified_dashboard_live.ex", :pattern_match}
]
