version: "3.9"

services:
  db:
    image: postgres:15-alpine
    container_name: eve_tracker_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: eve_tracker_dev
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./priv/repo/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: eve_tracker_redis
    command: ["redis-server", "--save", "900", "1", "--loglevel", "warning"]
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

  app:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    container_name: eve_tracker_app
    command: >
      bash -lc "
        echo 'Waiting for database...' &&
        while ! pg_isready -h db -U postgres; do sleep 1; done &&
        echo 'Database ready!' &&
        mix deps.get &&
        mix ecto.create --quiet &&
        mix ecto.migrate &&
        npm ci --prefix assets &&
        echo 'Starting Phoenix server...' &&
        mix phx.server
      "
    volumes:
      - .:/workspace:cached
      - node_modules:/workspace/assets/node_modules
      - mix_deps:/workspace/deps
      - mix_build:/workspace/_build
    working_dir: /workspace
    environment:
      - MIX_ENV=dev
      - DATABASE_URL=ecto://postgres:postgres@db/eve_tracker_dev
      - REDIS_URL=redis://redis:6379
      - PHX_HOST=localhost
      - PHX_PORT=4000
    env_file: 
      - .env
    ports:
      - "4000:4000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    stdin_open: true
    tty: true

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  node_modules:
    driver: local
  mix_deps:
    driver: local
  mix_build:
    driver: local 