import Config

# Load .env file for development if it exists (but not in test environment)
if File.exists?(".env") and Mix.env() != :test do
  try do
    ".env"
    |> File.read!()
    |> String.split("\n")
    |> Enum.each(fn line ->
      case String.trim(line) do
        "" ->
          nil

        # Skip comments
        "#" <> _ ->
          nil

        line ->
          case String.split(line, "=", parts: 2) do
            [key, value] -> System.put_env(key, value)
            _ -> nil
          end
      end
    end)
  rescue
    _ -> nil
  end
end

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :eve_dmv, EveDmvWeb.Endpoint,
  # Bind to 0.0.0.0 to expose the server to the docker host machine.
  # This makes make the service accessible from any network interface.
  # Change to `ip: {127, 0, 0, 1}` to allow access only from the server machine.
  http: [ip: {0, 0, 0, 0}, port: String.to_integer(System.get_env("PHX_PORT") || "4013")],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "iFDhYtSqjS/FcTaJVyRe5WKKe974ZMZoFWIbvIg8Mti5FW5HYpAFRHsAirJU5tz9",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:eve_dmv, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:eve_dmv, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :eve_dmv, EveDmvWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r"priv/static/(?!uploads/).*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/eve_dmv_web/(controllers|live|components)/.*(ex|heex)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :eve_dmv, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n", level: :debug

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include HEEx debug annotations as HTML comments in rendered markup
  debug_heex_annotations: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false

# Configure your database
config :eve_dmv, EveDmv.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "db",
  database: "eve_tracker_gamma",
  port: 5432,
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  # Connection pool configuration
  pool_size: 20,
  queue_target: 50,
  queue_interval: 1000,
  timeout: 15_000,
  ownership_timeout: 20_000,
  pool_timeout: 5_000

# Development-specific killmail pipeline configuration
# Note: These will be overridden by runtime.exs if .env files exist
config :eve_dmv,
  wanderer_kills_sse_url: System.get_env("WANDERER_KILLS_SSE_URL", "http://localhost:8080/sse"),
  wanderer_kills_websocket_url:
    System.get_env("WANDERER_KILLS_WS_URL", "ws://localhost:4004/socket"),
  wanderer_kills_base_url:
    System.get_env("WANDERER_KILLS_BASE_URL", "http://host.docker.internal:4004"),
  pipeline_enabled: System.get_env("PIPELINE_ENABLED", "true") == "true",
  mock_sse_server_enabled: System.get_env("MOCK_SSE_SERVER_ENABLED", "false") == "true"
