defmodule EveDmv.Repo.Migrations.CreateCharacterStats do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:character_stats, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true
      add :character_id, :bigint, null: false
      add :character_name, :text, null: false
      add :corporation_id, :bigint
      add :corporation_name, :text
      add :alliance_id, :bigint
      add :alliance_name, :text
      add :total_kills, :bigint, default: 0
      add :total_losses, :bigint, default: 0
      add :solo_kills, :bigint, default: 0
      add :solo_losses, :bigint, default: 0
      add :ship_usage, :map, default: %{}
      add :frequent_associates, :map, default: %{}
      add :active_systems, :map, default: %{}
      add :target_profile, :map, default: %{}
      add :aggression_index, :float, default: 5.0
      add :avg_gang_size, :float, default: 1.0
      add :prime_timezone, :text
      add :home_system_id, :bigint
      add :home_system_name, :text
      add :uses_cynos, :boolean, default: false
      add :flies_capitals, :boolean, default: false
      add :has_logi_support, :boolean, default: false
      add :batphone_probability, :text, default: "low"
      add :isk_efficiency, :float, default: 50.0
      add :kill_death_ratio, :float, default: 1.0
      add :dangerous_rating, :bigint, default: 3
      add :identified_weaknesses, :map, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :last_calculated_at, :utc_datetime_usec
      add :data_completeness, :bigint, default: 0
    end
  end

  def down do
    drop table(:character_stats)
  end
end
