defmodule :"Elixir.EveDmv.Repo.Migrations.03AnalyticsSchema" do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:ship_stats, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:ship_type_id, :bigint, null: false)
      add(:ship_name, :text, null: false)
      add(:ship_category, :text, null: false)
      add(:tech_level, :bigint, default: 1)
      add(:meta_level, :bigint, default: 0)
      add(:is_capital, :boolean, default: false)
      add(:total_kills, :bigint, default: 0)
      add(:total_losses, :bigint, default: 0)
      add(:solo_kills, :bigint, default: 0)
      add(:pilots_flown, :bigint, default: 0)
      add(:total_isk_destroyed, :decimal, default: "0.0", precision: 20, scale: 2)
      add(:total_isk_lost, :decimal, default: "0.0", precision: 20, scale: 2)
      add(:avg_kill_value, :decimal, default: "0.0", precision: 15, scale: 2)
      add(:avg_loss_value, :decimal, default: "0.0", precision: 15, scale: 2)
      add(:kill_death_ratio, :decimal, default: "0.0", precision: 10, scale: 2)
      add(:isk_efficiency_percent, :decimal, default: "0.0", precision: 5, scale: 2)
      add(:survival_rate_percent, :decimal, default: "0.0", precision: 5, scale: 2)
      add(:avg_damage_dealt, :decimal, default: "0.0", precision: 12, scale: 2)
      add(:avg_gang_size_when_killing, :decimal, default: "1.0", precision: 6, scale: 2)
      add(:avg_gang_size_when_dying, :decimal, default: "1.0", precision: 6, scale: 2)
      add(:solo_kill_percentage, :decimal, default: "0.0", precision: 5, scale: 2)
      add(:most_killed_ship_type_id, :bigint)
      add(:most_killed_ship_name, :text)
      add(:most_killed_by_ship_type_id, :bigint)
      add(:most_killed_by_ship_name, :text)
      add(:most_active_region_id, :bigint)
      add(:most_active_region_name, :text)
      add(:peak_activity_hour, :bigint)
      add(:usage_rank, :bigint)
      add(:effectiveness_rank, :bigint)
      add(:popularity_trend, :text, default: "stable")
      add(:meta_tier, :text, default: "unranked")
      add(:role_classification, :text, default: "mixed")
      add(:first_seen, :utc_datetime)
      add(:last_seen, :utc_datetime)
      add(:stats_period_start, :utc_datetime)
      add(:stats_period_end, :utc_datetime)
      add(:last_updated, :utc_datetime, default: fragment("(now() AT TIME ZONE 'utc')"))

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create(unique_index(:ship_stats, [:ship_type_id], name: "ship_stats_unique_ship_index"))

    create table(:player_stats, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:character_id, :bigint, null: false)
      add(:character_name, :text, null: false)
      add(:total_kills, :bigint, default: 0)
      add(:total_losses, :bigint, default: 0)
      add(:solo_kills, :bigint, default: 0)
      add(:solo_losses, :bigint, default: 0)
      add(:gang_kills, :bigint, default: 0)
      add(:gang_losses, :bigint, default: 0)
      add(:total_isk_destroyed, :decimal, default: "0.0", precision: 20, scale: 2)
      add(:total_isk_lost, :decimal, default: "0.0", precision: 20, scale: 2)
      add(:kill_death_ratio, :decimal, default: "0.0", precision: 10, scale: 2)
      add(:isk_efficiency_percent, :decimal, default: "0.0", precision: 5, scale: 2)
      add(:solo_performance_ratio, :decimal, default: "0.0", precision: 10, scale: 2)
      add(:first_kill_date, :utc_datetime)
      add(:last_kill_date, :utc_datetime)
      add(:active_days, :bigint, default: 0)
      add(:avg_kills_per_week, :decimal, default: "0.0", precision: 8, scale: 2)
      add(:ship_types_used, :bigint, default: 0)
      add(:favorite_ship_type_id, :bigint)
      add(:favorite_ship_name, :text)
      add(:avg_gang_size, :decimal, default: "1.0", precision: 6, scale: 2)
      add(:preferred_gang_size, :text, default: "solo")
      add(:active_regions, :bigint, default: 0)
      add(:home_region_id, :bigint)
      add(:home_region_name, :text)
      add(:danger_rating, :bigint, default: 1)
      add(:primary_activity, :text, default: "solo_pvp")
      add(:stats_period_start, :utc_datetime)
      add(:stats_period_end, :utc_datetime)
      add(:last_updated, :utc_datetime, default: fragment("(now() AT TIME ZONE 'utc')"))

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create(
      unique_index(:player_stats, [:character_id], name: "player_stats_unique_character_index")
    )
  end

  def down do
    drop_if_exists(
      unique_index(:player_stats, [:character_id], name: "player_stats_unique_character_index")
    )

    drop(table(:player_stats))

    drop_if_exists(
      unique_index(:ship_stats, [:ship_type_id], name: "ship_stats_unique_ship_index")
    )

    drop(table(:ship_stats))
  end
end
