defmodule EveDmv.Repo.Migrations.CreateFleetDoctrines do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:fleet_doctrines, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:name, :text, null: false)
      add(:description, :text)
      add(:doctrine_type, :text, null: false, default: "roam")
      add(:ship_requirements, :map, null: false, default: %{})
      add(:role_requirements, :map, null: false, default: %{})
      add(:optional_ships, {:array, :bigint}, null: false, default: [])
      add(:mass_limits, :map, null: false, default: %{})
      add(:mass_category, :text, null: false, default: "medium")
      add(:minimum_pilots, :bigint, null: false, default: 5)
      add(:optimal_pilots, :bigint)
      add(:corporation_id, :bigint)
      add(:is_active, :boolean, null: false, default: true)
      add(:is_public, :boolean, null: false, default: false)
      add(:created_by, :bigint, null: false)
      add(:usage_count, :bigint, null: false, default: 0)
      add(:effectiveness_rating, :float)
      add(:tags, {:array, :text}, null: false, default: [])
      add(:fitting_notes, :text)

      add(:created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:last_used_at, :utc_datetime)
    end

    create(
      unique_index(:fleet_doctrines, [:name, :corporation_id],
        name: "fleet_doctrines_unique_name_per_corp_index"
      )
    )
  end

  def down do
    drop_if_exists(
      unique_index(:fleet_doctrines, [:name, :corporation_id],
        name: "fleet_doctrines_unique_name_per_corp_index"
      )
    )

    drop(table(:fleet_doctrines))
  end
end
