defmodule EveDmv.Repo.Migrations.UpdateKillmailConstraints do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists(
      unique_index(:killmails_raw, [:killmail_id, :killmail_time],
        name: "killmails_raw_unique_killmail_index"
      )
    )

    create(
      unique_index(:killmails_raw, [:killmail_id], name: "killmails_raw_unique_killmail_id_index")
    )
  end

  def down do
    drop_if_exists(
      unique_index(:killmails_raw, [:killmail_id], name: "killmails_raw_unique_killmail_id_index")
    )

    create(
      unique_index(:killmails_raw, [:killmail_id, :killmail_time],
        name: "killmails_raw_unique_killmail_index"
      )
    )
  end
end
