defmodule EveDmv.Repo.Migrations.RemoveParticipantForeignKeys do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint(:participants, "participants_weapon_type_id_fkey")

    drop constraint(:participants, "participants_ship_type_id_fkey")

    alter table(:participants) do
      modify :weapon_type_id, :bigint
      modify :ship_type_id, :bigint
    end

    create index(:participants, [:ship_type_id])

    create index(:participants, [:weapon_type_id])

    create unique_index(:killmails_enriched, [:killmail_id, :killmail_time],
             name: "killmails_enriched_unique_killmail_index"
           )

    create unique_index(:eve_item_types, [:type_id], name: "eve_item_types_type_id_index")
  end

  def down do
    drop_if_exists unique_index(:eve_item_types, [:type_id], name: "eve_item_types_type_id_index")

    drop_if_exists unique_index(:killmails_enriched, [:killmail_id, :killmail_time],
                     name: "killmails_enriched_unique_killmail_index"
                   )

    drop_if_exists index(:participants, [:weapon_type_id])

    drop_if_exists index(:participants, [:ship_type_id])

    alter table(:participants) do
      modify :ship_type_id,
             references(:eve_item_types,
               column: :type_id,
               name: "participants_ship_type_id_fkey",
               type: :bigint,
               prefix: "public"
             )

      modify :weapon_type_id,
             references(:eve_item_types,
               column: :type_id,
               name: "participants_weapon_type_id_fkey",
               type: :bigint,
               prefix: "public"
             )
    end
  end
end
