defmodule EveDmv.Repo.Migrations.UpdateSolarSystemPrecision do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    # Just update the solar system precision for now
    # The participant foreign key will be handled separately
    alter table(:eve_solar_systems) do
      modify :z, :decimal, precision: 25, scale: 2
      modify :y, :decimal, precision: 25, scale: 2
      modify :x, :decimal, precision: 25, scale: 2
      modify :security_status, :decimal, precision: 15, scale: 10
    end
  end

  def down do
    alter table(:eve_solar_systems) do
      modify :security_status, :decimal, precision: 10, scale: 6
      modify :x, :decimal, precision: 20, scale: 6
      modify :y, :decimal, precision: 20, scale: 6
      modify :z, :decimal, precision: 20, scale: 6
    end
  end
end
