defmodule EveDmv.Repo.Migrations.AddHomeDefenseAnalytics do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:home_defense_analytics, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :corporation_id, :bigint, null: false
      add :corporation_name, :text, null: false
      add :alliance_id, :bigint
      add :alliance_name, :text
      add :home_system_id, :bigint
      add :home_system_name, :text
      add :analysis_period_start, :utc_datetime, null: false
      add :analysis_period_end, :utc_datetime, null: false
      add :analysis_requested_by, :bigint
      add :last_updated_at, :utc_datetime, default: fragment("(now() AT TIME ZONE 'utc')")
      add :overall_defense_score, :bigint, default: 50
      add :timezone_coverage_score, :bigint, default: 0
      add :response_time_score, :bigint, default: 0
      add :rolling_competency_score, :bigint, default: 0
      add :member_participation_score, :bigint, default: 0
      add :timezone_coverage, :map, default: %{}
      add :rolling_participation, :map, default: %{}
      add :response_metrics, :map, default: %{}
      add :member_activity_patterns, :map, default: %{}
      add :defensive_capabilities, :map, default: %{}
      add :coverage_gaps, :map, default: %{}
      add :total_members_analyzed, :bigint, default: 0
      add :active_members_count, :bigint, default: 0
      add :critical_gaps_count, :bigint, default: 0
      add :data_completeness_percent, :bigint, default: 0

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create index(:home_defense_analytics, [:coverage_gaps],
             name: "home_defense_coverage_gaps_gin_idx",
             using: "gin"
           )

    create index(:home_defense_analytics, [:defensive_capabilities],
             name: "home_defense_capabilities_gin_idx",
             using: "gin"
           )

    create index(:home_defense_analytics, [:member_activity_patterns],
             name: "home_defense_member_activity_gin_idx",
             using: "gin"
           )

    create index(:home_defense_analytics, [:response_metrics],
             name: "home_defense_response_metrics_gin_idx",
             using: "gin"
           )

    create index(:home_defense_analytics, [:rolling_participation],
             name: "home_defense_rolling_participation_gin_idx",
             using: "gin"
           )

    create index(:home_defense_analytics, [:timezone_coverage],
             name: "home_defense_timezone_coverage_gin_idx",
             using: "gin"
           )

    create index(:home_defense_analytics, [:overall_defense_score])

    create index(:home_defense_analytics, [:analysis_period_end])

    create index(:home_defense_analytics, [:analysis_period_start])

    create index(:home_defense_analytics, [:alliance_id])

    create index(:home_defense_analytics, [:corporation_id], unique: true)
  end

  def down do
    drop_if_exists index(:home_defense_analytics, [:corporation_id])

    drop_if_exists index(:home_defense_analytics, [:alliance_id])

    drop_if_exists index(:home_defense_analytics, [:analysis_period_start])

    drop_if_exists index(:home_defense_analytics, [:analysis_period_end])

    drop_if_exists index(:home_defense_analytics, [:overall_defense_score])

    drop_if_exists index(:home_defense_analytics, [:timezone_coverage],
                     name: "home_defense_timezone_coverage_gin_idx"
                   )

    drop_if_exists index(:home_defense_analytics, [:rolling_participation],
                     name: "home_defense_rolling_participation_gin_idx"
                   )

    drop_if_exists index(:home_defense_analytics, [:response_metrics],
                     name: "home_defense_response_metrics_gin_idx"
                   )

    drop_if_exists index(:home_defense_analytics, [:member_activity_patterns],
                     name: "home_defense_member_activity_gin_idx"
                   )

    drop_if_exists index(:home_defense_analytics, [:defensive_capabilities],
                     name: "home_defense_capabilities_gin_idx"
                   )

    drop_if_exists index(:home_defense_analytics, [:coverage_gaps],
                     name: "home_defense_coverage_gaps_gin_idx"
                   )

    drop table(:home_defense_analytics)
  end
end
