defmodule :"Elixir.EveDmv.Repo.Migrations.04BattleAnalysisSchema" do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:ship_fittings, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:name, :text, null: false)
      add(:ship_type_id, :bigint, null: false)
      add(:character_id, :bigint)
      add(:source, :text, default: "manual")
      add(:raw_fitting, :text, null: false)
      add(:parsed_fitting, :map, default: %{})
      add(:calculated_stats, :map, default: %{})
      add(:last_calculated, :utc_datetime_usec)
      add(:tags, {:array, :text}, default: [])
      add(:is_public, :boolean, default: false)
      add(:usage_count, :bigint, default: 0)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create table(:combat_logs, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:pilot_name, :text, null: false)
      add(:uploaded_at, :utc_datetime_usec, null: false)
      add(:file_name, :text)
      add(:file_size, :bigint)
      add(:start_time, :utc_datetime_usec)
      add(:end_time, :utc_datetime_usec)
      add(:raw_content, :text, null: false)
      add(:content_hash, :text, null: false)
      add(:parsed_data, :map, default: %{})
      add(:event_count, :bigint, default: 0)
      add(:parse_status, :text, default: "pending")
      add(:parse_error, :text)
      add(:summary, :map, default: %{})
      add(:performance_metrics, :map, default: %{})
      add(:battle_id, :text)
      add(:battle_correlation, :map, default: %{})

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create table(:battles, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:battle_id, :text, null: false)
      add(:system_id, :bigint)
      add(:constellation_id, :bigint)
      add(:region_id, :bigint)
      add(:start_time, :utc_datetime)
      add(:end_time, :utc_datetime)
      add(:participant_count, :bigint, default: 0)
      add(:total_isk_destroyed, :bigint, default: 0)
      add(:battle_type, :text)
      add(:metadata, :map, default: %{})
      add(:deleted_at, :utc_datetime)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create(
      unique_index(:battles, [:battle_id],
        where: "(deleted_at IS NULL)",
        name: "battles_unique_battle_id_index"
      )
    )

    create table(:battle_killmails, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)

      add(
        :battle_id,
        references(:battles,
          column: :id,
          name: "battle_killmails_battle_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )

      add(
        :killmail_id,
        references(:killmails_raw,
          column: :killmail_id,
          name: "battle_killmails_killmail_id_fkey",
          type: :bigint,
          prefix: "public"
        ),
        null: false
      )

      add(:added_at, :utc_datetime, null: false, default: fragment("(now() AT TIME ZONE 'utc')"))

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create(
      unique_index(:battle_killmails, [:battle_id, :killmail_id],
        name: "battle_killmails_unique_battle_killmail_index"
      )
    )
  end

  def down do
    drop_if_exists(
      unique_index(:battle_killmails, [:battle_id, :killmail_id],
        name: "battle_killmails_unique_battle_killmail_index"
      )
    )

    drop(constraint(:battle_killmails, "battle_killmails_battle_id_fkey"))

    drop(constraint(:battle_killmails, "battle_killmails_killmail_id_fkey"))

    drop(table(:battle_killmails))

    drop_if_exists(unique_index(:battles, [:battle_id], name: "battles_unique_battle_id_index"))

    drop(table(:battles))

    drop(table(:combat_logs))

    drop(table(:ship_fittings))
  end
end
