defmodule EveDmv.Repo.Migrations.AddWeaponTypeForeignKey do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:participants) do
      modify :weapon_type_id,
             references(:eve_item_types,
               column: :type_id,
               name: "participants_weapon_type_id_fkey",
               type: :bigint,
               prefix: "public"
             )
    end

    create_if_not_exists index(:participants, [:weapon_type_id])
  end

  def down do
    drop_if_exists index(:participants, [:weapon_type_id])

    drop constraint(:participants, "participants_weapon_type_id_fkey")

    alter table(:participants) do
      modify :weapon_type_id, :bigint
    end
  end
end
