defmodule EveDmv.Repo.Migrations.Somthing do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:character_stats) do
      add(:awox_probability, :float, default: 0.0)
    end
  end

  def down do
    alter table(:character_stats) do
      remove(:awox_probability)
    end
  end
end
